/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QC_STORM_ */

#ifndef _Included_QC_STORM_
#define _Included_QC_STORM_
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     QC_STORM_
	* Method:    lm_SetImagePara
	* Signature: (IIIII[C)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetImagePara
	(JNIEnv *, jclass, jint, jint, jint, jint, jint, jstring);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetLocPara
	* Signature: (FFFIIIIIFFFF)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetLocPara
	(JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetLocPara3D
	* Signature: (FFFFFFFFFFFFF)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetLocPara3D
	(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetLocParaDH3D
	* Signature: (IFF)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetLocParaDH3D
	(JNIEnv *, jclass, jint, jfloat, jfloat);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetStatInfSelection
	* Signature: (II)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetStatInfSelection
	(JNIEnv *, jclass, jint, jint);

	/*
	* Class:     QC_STORM_
	* Method:    lm_StartLocThread
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1StartLocThread
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_StopLocThread
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1StopLocThread
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetMaxDispVal
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_QC_1STORM_1_lm_1GetMaxDispVal
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_FeedImageData
	* Signature: ([SI)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1FeedImageData
	(JNIEnv *, jclass, jshortArray, jint);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetSMLMImage
	* Signature: ()[F
	*/
	JNIEXPORT jfloatArray JNICALL Java_QC_1STORM_1_lm_1GetSMLMImage
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetSMLMImage3D
	* Signature: ()[I
	*/
	JNIEXPORT jintArray JNICALL Java_QC_1STORM_1_lm_1GetSMLMImage3D
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetSpatialResolutionInf
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetSpatialResolutionInf
	(JNIEnv *, jclass, jfloat);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetStatInfImageSize
	* Signature: ()[I
	*/
	JNIEXPORT jintArray JNICALL Java_QC_1STORM_1_lm_1GetStatInfImageSize
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetStatInfImage
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_QC_1STORM_1_lm_1GetStatInfImage
	(JNIEnv *, jclass, jint);

	/*
	* Class:     QC_STORM_
	* Method:    lm_IsLocFinish
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_QC_1STORM_1_lm_1IsLocFinish
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetRerendImagePara
	* Signature: ([CII)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1SetRerendImagePara
	(JNIEnv *, jclass, jstring, jint, jint);

	/*
	* Class:     QC_STORM_
	* Method:    lm_StartRerend
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1StartRerend
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_GetRerendImageInf
	* Signature: ()[I
	*/
	JNIEXPORT jintArray JNICALL Java_QC_1STORM_1_lm_1GetRerendImageInf
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_ReleaseRerendResource
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1ReleaseRerendResource
	(JNIEnv *, jclass);

	/*
	* Class:     QC_STORM_
	* Method:    lm_SetImagePara
	* Signature: (III[C)V
	*/
	JNIEXPORT void JNICALL Java_QC_1STORM_1_lm_1StartBatchImageLoc
	(JNIEnv *env, jclass obj, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
