/*
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU LESSER GENERAL PUBLIC LICENSE for more details.

You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

//package QC_STORM;


import ij.io.OpenDialog;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;



public class QC_STORM_Configurator extends javax.swing.JFrame {
    
    volatile public int PluginStatus; // 0: open, 1: process, 2: closed
    public QC_STORM_Parameters.LocalizationPara LocPara;

    final String LocParafileName = "QC_STORM\\QC_STORM_IJ_para.properties";

    volatile public String ResultsFilePath = "D:\\";
    
    public String RerendLocDataPath = null;
    
    public int RerendMode = 0; // 0: single file, 1: dir
    
    
    public QC_STORM_ fa_QC_STORM_;
    
    public int DriftCorrEnableI=0;
    public int DriftCorrGroupFrameNum=800;
    
    public float ZDepthGapF=50;
    public int FramePerDepth=100;
    
    
    /**
     * Creates new form QC_STORM_Configurator
     */
    public QC_STORM_Configurator() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QC-STORM");
        
        LocPara = new QC_STORM_Parameters.LocalizationPara();
        PluginStatus = 0;
        this.addWindowListener(new MyListener());
        
        try {
            LoadPropertyFile(GetParaFileSavePath());
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
           
        }

    }
    public QC_STORM_Configurator(QC_STORM_ fa_OnlineSMLM) {
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QC-STORM");
        
        fa_QC_STORM_ = fa_OnlineSMLM;
        
        LocPara = new QC_STORM_Parameters.LocalizationPara();
        PluginStatus = 0;
        this.addWindowListener(new MyListener());
        
        try {
            LoadPropertyFile(GetParaFileSavePath());
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
           
        }
        
        jTabbedPane1.remove(jPanel_ROMP);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jTextField_ParaFile1 = new javax.swing.JTextField();
        jButton_Start2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField_p2_XLY1 = new javax.swing.JTextField();
        jButton_Start = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_RegionSize = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField_RawPixelSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_RenderPixelSize = new javax.swing.JTextField();
        jTextField_SNR_th = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_LocType = new javax.swing.JComboBox();
        jCheckBox_Stat_ConsecutiveFitEn = new javax.swing.JCheckBox();
        jButton_LoadParaFile = new javax.swing.JButton();
        jTextField_ParaFile = new javax.swing.JTextField();
        jTextField_ResultPath = new javax.swing.JTextField();
        jButton_LoadResultPath = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField_ConsecFilterRadius = new javax.swing.JTextField();
        jCheckBox_Stat_MultiFitEn = new javax.swing.JCheckBox();
        jCheckBox_Stat_WLEDisable = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Offset = new javax.swing.JTextField();
        jTextField_Kadc = new javax.swing.JTextField();
        jTextField_QE = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_MaxZDepth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_p2_XGY = new javax.swing.JTextField();
        jTextField_p3_XGY = new javax.swing.JTextField();
        jTextField_p4_XGY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_p0_XGY = new javax.swing.JTextField();
        jTextField_p1_XGY = new javax.swing.JTextField();
        jTextField_MinZDepth = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField_ZDepthCorrFactor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_p4_XLY = new javax.swing.JTextField();
        jTextField_p3_XLY = new javax.swing.JTextField();
        jTextField_p2_XLY = new javax.swing.JTextField();
        jTextField_p1_XLY = new javax.swing.JTextField();
        jTextField_p0_XLY = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField_DH_MeanDistance = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField_DH_DistanceTh = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jComboBox_DH_RotationType = new javax.swing.JComboBox();
        jPanel_ROMP = new javax.swing.JPanel();
        jCheckBox_Stat_SpaResolutionEn = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jTextField_StructureSize2D = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox_Stat_SpaResolutionVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_NyqResolutionVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_DimensionFDVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_LocDensityFDVary = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox_Stat_TotalPhoton = new javax.swing.JCheckBox();
        jCheckBox_Stat_LocPrec = new javax.swing.JCheckBox();
        jCheckBox_Stat_PSFWidth = new javax.swing.JCheckBox();
        jCheckBox_Stat_SNR = new javax.swing.JCheckBox();
        jCheckBox_Stat_TotalPhotonVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_LocPrecVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_OntimeVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_SNRVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_PSFWidthVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_LocDensityVary = new javax.swing.JCheckBox();
        jCheckBox_Stat_BackgroundVary = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField_LocDataPath = new javax.swing.JTextField();
        jButton_LoadLocData = new javax.swing.JButton();
        jCheckBox_ShiftCorrection = new javax.swing.JCheckBox();
        jButton_Rerend = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField_DriftCorrGroupFrameNum = new javax.swing.JTextField();
        jTextField_LocDataDir = new javax.swing.JTextField();
        jButton_LoadLocDir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jButton_Start2.setText("Rerendering");
        jButton_Start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Start2ActionPerformed(evt);
            }
        });

        jLabel28.setText("Z depth correction factor:");

        jTextField_p2_XLY1.setText("13.08");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton_Start.setText("Start localization");
        jButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartActionPerformed(evt);
            }
        });

        jLabel1.setText("Fitting ROI size (pixels):");

        jComboBox_RegionSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "7", "9", "11", "13", "15", "17" }));
        jComboBox_RegionSize.setSelectedIndex(1);
        jComboBox_RegionSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RegionSizeActionPerformed(evt);
            }
        });

        jLabel2.setText("Raw image pixel size (nm):");

        jTextField_RawPixelSize.setText("100");

        jLabel3.setText("Rendering pixel size (nm):");

        jTextField_RenderPixelSize.setText("10");
        jTextField_RenderPixelSize.setToolTipText("Pixel Zoom from raw image to SR image");
        jTextField_RenderPixelSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RenderPixelSizeActionPerformed(evt);
            }
        });

        jTextField_SNR_th.setText("5");

        jLabel20.setText("Rendering SNR threshold:");

        jLabel21.setText("Fitting type:");

        jComboBox_LocType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gaussian 2D", "Astigmatism 3D", "Double-Helix 3D" }));
        jComboBox_LocType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_LocTypeActionPerformed(evt);
            }
        });

        jCheckBox_Stat_ConsecutiveFitEn.setText("Consecutive fitting (temporal grouping)");

        jButton_LoadParaFile.setText("Load configuration file");
        jButton_LoadParaFile.setActionCommand("");
        jButton_LoadParaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadParaFileActionPerformed(evt);
            }
        });

        jTextField_ResultPath.setText("D:\\");

            jButton_LoadResultPath.setText("Change results save path");
            jButton_LoadResultPath.setActionCommand("");
            jButton_LoadResultPath.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_LoadResultPathActionPerformed(evt);
                }
            });

            jLabel29.setText("Consecutive fitting radius (nm):");

            jTextField_ConsecFilterRadius.setText("80");

            jCheckBox_Stat_MultiFitEn.setText("Multi-emitter fitting");

            jCheckBox_Stat_WLEDisable.setText("Low SNR image, disable WLE");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_ConsecutiveFitEn)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField_ResultPath, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_ParaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_LoadParaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_LoadResultPath, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_ConsecFilterRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_LocType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_SNR_th, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_RenderPixelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_RawPixelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_RegionSize, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_Stat_WLEDisable)))
                        .addComponent(jCheckBox_Stat_MultiFitEn))
                    .addContainerGap(88, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox_RegionSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_RawPixelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField_RenderPixelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_SNR_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox_LocType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_MultiFitEn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox_Stat_WLEDisable, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox_Stat_ConsecutiveFitEn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_ConsecFilterRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ResultPath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_LoadResultPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ParaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_LoadParaFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(91, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Imaging", jPanel1);

            jLabel13.setText("QE:");

            jLabel14.setText("Kadc (e-/DN):");

            jLabel15.setText("Offset (DN):");

            jTextField_Offset.setText("100");

            jTextField_Kadc.setText("0.45");

            jTextField_QE.setText("0.72");

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(54, 54, 54)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Kadc)
                        .addComponent(jTextField_QE, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(jTextField_Offset))
                    .addGap(265, 265, 265))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jTextField_QE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Kadc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addContainerGap(285, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Camera", jPanel5);

            jLabel4.setText("Z depth rendering range (nm):");

            jTextField_MaxZDepth.setText("500");
            jTextField_MaxZDepth.setToolTipText("Max Z depth");

            jLabel10.setText("Z depth calibration curve by 4 order polynomial:");

            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("p4:");

            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("p3:");

            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("p2:");

            jTextField_p2_XGY.setText("13.08");

            jTextField_p3_XGY.setText("-4.2170");

            jTextField_p4_XGY.setText("0");

            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel8.setText("p1:");

            jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel9.setText("p0:");

            jTextField_p0_XGY.setText("0");

            jTextField_p1_XGY.setText("-278.79");

            jTextField_MinZDepth.setText("-500");
            jTextField_MinZDepth.setToolTipText("Min Z depth");

            jLabel18.setText("Z depth correction factor:");

            jTextField_ZDepthCorrFactor.setText("1.0");
            jTextField_ZDepthCorrFactor.setToolTipText("Min Z depth");

            jLabel22.setText("part1, PSF SigmaX > PSF SigmaY (Shared by double-helix):");

            jLabel23.setText("Z = p4*d^4 + ... + p0*d^0, d = SigmaX^2 - SigmaY^2 or rotation angle ");

            jLabel24.setText("part2, PSF SigmaX < PSF SigmaY:");

            jTextField_p4_XLY.setText("0");

            jTextField_p3_XLY.setText("-4.2170");

            jTextField_p2_XLY.setText("13.08");

            jTextField_p1_XLY.setText("-278.79");

            jTextField_p0_XLY.setText("0");

            jLabel30.setText("Double-helix special:");

            jLabel31.setText("Mean distance (pixel):");

            jTextField_DH_MeanDistance.setText("10.0");

            jLabel32.setText("Distance vary th (pixel):");

            jTextField_DH_DistanceTh.setText("1.5");

            jLabel33.setText("Rotation type:");

            jComboBox_DH_RotationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 - pi, focal = pi/2", "-pi/2 - pi/2, focal = 0", " " }));
            jComboBox_DH_RotationType.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox_DH_RotationTypeActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(208, 208, 208)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_DH_DistanceTh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_DH_RotationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_DH_MeanDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel18))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel4)
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_ZDepthCorrFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField_MinZDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_MaxZDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(141, 141, 141))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(377, 377, 377)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(57, 57, 57))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31)
                                .addComponent(jLabel32)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_p4_XGY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_p3_XGY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_p2_XGY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_p1_XLY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField_p1_XGY, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addGap(20, 20, 20))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(208, 208, 208)
                                    .addComponent(jTextField_p2_XLY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jTextField_p4_XLY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_p3_XLY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_p0_XGY, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p0_XLY, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(58, 58, 58))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_MinZDepth, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_MaxZDepth, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_ZDepthCorrFactor)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(9, 9, 9)
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_p0_XGY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p1_XGY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p2_XGY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p3_XGY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p4_XGY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel24)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_p4_XLY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p3_XLY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p2_XLY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p1_XLY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_p0_XLY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(jLabel30)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_DH_RotationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_DH_MeanDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_DH_DistanceTh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(51, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("3D", jPanel2);

            jCheckBox_Stat_SpaResolutionEn.setText("Spatial resolution calculation");

            jLabel26.setText("Structure size 2D (nm):");

            jTextField_StructureSize2D.setText("50");
            jTextField_StructureSize2D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField_StructureSize2DActionPerformed(evt);
                }
            });

            jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel16.setText("Spatial resolution time-varying curve:");

            jCheckBox_Stat_SpaResolutionVary.setText("Spatial resolution (Lateral)");

            jCheckBox_Stat_NyqResolutionVary.setText("Nyquist resolution");
            jCheckBox_Stat_NyqResolutionVary.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox_Stat_NyqResolutionVaryActionPerformed(evt);
                }
            });

            jCheckBox_Stat_DimensionFDVary.setText("Dimension FD");

            jCheckBox_Stat_LocDensityFDVary.setText("Localization density FD");

            javax.swing.GroupLayout jPanel_ROMPLayout = new javax.swing.GroupLayout(jPanel_ROMP);
            jPanel_ROMP.setLayout(jPanel_ROMPLayout);
            jPanel_ROMPLayout.setHorizontalGroup(
                jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ROMPLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_SpaResolutionEn)
                        .addGroup(jPanel_ROMPLayout.createSequentialGroup()
                            .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Stat_SpaResolutionVary)
                                .addComponent(jCheckBox_Stat_DimensionFDVary)
                                .addComponent(jLabel16)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_StructureSize2D, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_Stat_NyqResolutionVary)
                                .addComponent(jCheckBox_Stat_LocDensityFDVary))))
                    .addContainerGap(110, Short.MAX_VALUE))
            );
            jPanel_ROMPLayout.setVerticalGroup(
                jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ROMPLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jCheckBox_Stat_SpaResolutionEn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_StructureSize2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_SpaResolutionVary)
                        .addComponent(jCheckBox_Stat_NyqResolutionVary))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel_ROMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_DimensionFDVary)
                        .addComponent(jCheckBox_Stat_LocDensityFDVary))
                    .addContainerGap(246, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("ROMP", jPanel_ROMP);

            jCheckBox_Stat_TotalPhoton.setSelected(true);
            jCheckBox_Stat_TotalPhoton.setText("Total photon");

            jCheckBox_Stat_LocPrec.setText("Localization precision");

            jCheckBox_Stat_PSFWidth.setText("PSF width");

            jCheckBox_Stat_SNR.setSelected(true);
            jCheckBox_Stat_SNR.setText("SNR");

            jCheckBox_Stat_TotalPhotonVary.setSelected(true);
            jCheckBox_Stat_TotalPhotonVary.setText("Total photon");

            jCheckBox_Stat_LocPrecVary.setSelected(true);
            jCheckBox_Stat_LocPrecVary.setText("Localization precision");

            jCheckBox_Stat_OntimeVary.setText("Ontime");
            jCheckBox_Stat_OntimeVary.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox_Stat_OntimeVaryActionPerformed(evt);
                }
            });

            jCheckBox_Stat_SNRVary.setSelected(true);
            jCheckBox_Stat_SNRVary.setText("SNR");

            jCheckBox_Stat_PSFWidthVary.setSelected(true);
            jCheckBox_Stat_PSFWidthVary.setText("PSF width");

            jCheckBox_Stat_LocDensityVary.setSelected(true);
            jCheckBox_Stat_LocDensityVary.setText("Localization density 2D");

            jCheckBox_Stat_BackgroundVary.setText("Background");

            jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel11.setText("Histogram:");

            jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel12.setText("Time-varying curve:");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox_Stat_TotalPhoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox_Stat_SNR, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Stat_PSFWidth)
                                .addComponent(jCheckBox_Stat_LocPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Stat_BackgroundVary)
                                .addComponent(jCheckBox_Stat_PSFWidthVary)
                                .addComponent(jCheckBox_Stat_OntimeVary)
                                .addComponent(jCheckBox_Stat_TotalPhotonVary))
                            .addGap(47, 47, 47)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Stat_LocDensityVary)
                                .addComponent(jCheckBox_Stat_LocPrecVary)
                                .addComponent(jCheckBox_Stat_SNRVary))))
                    .addContainerGap(151, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox_Stat_TotalPhoton)
                        .addComponent(jCheckBox_Stat_LocPrec))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox_Stat_SNR)
                        .addComponent(jCheckBox_Stat_PSFWidth))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel12)
                    .addGap(9, 9, 9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_TotalPhotonVary)
                        .addComponent(jCheckBox_Stat_LocPrecVary))
                    .addGap(3, 3, 3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_OntimeVary)
                        .addComponent(jCheckBox_Stat_SNRVary))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox_Stat_PSFWidthVary)
                        .addComponent(jCheckBox_Stat_LocDensityVary))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox_Stat_BackgroundVary)
                    .addContainerGap(206, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Statistics", jPanel3);

            jTextField_LocDataPath.setToolTipText("targer binary txt file");

            jButton_LoadLocData.setText("Load localization result file");
            jButton_LoadLocData.setToolTipText("targer binary txt file");
            jButton_LoadLocData.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_LoadLocDataActionPerformed(evt);
                }
            });

            jCheckBox_ShiftCorrection.setText("Drift correction by cross correlation");

            jButton_Rerend.setText("Rerendering");
            jButton_Rerend.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_RerendActionPerformed(evt);
                }
            });

            jLabel17.setText("Drift corr group frame number:");

            jTextField_DriftCorrGroupFrameNum.setText("1000");

            jTextField_LocDataDir.setToolTipText("binary txt files in a folder, no other txt files");

            jButton_LoadLocDir.setText("Load localization results dir");
            jButton_LoadLocDir.setToolTipText("binary txt files in a folder, no other txt files");
            jButton_LoadLocDir.setActionCommand("");
            jButton_LoadLocDir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_LoadLocDirActionPerformed(evt);
                }
            });

            jLabel25.setText("Single file rendering:");

            jLabel27.setText("Multi-files rendering:");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(jCheckBox_ShiftCorrection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_LocDataDir, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(jTextField_LocDataPath)
                        .addComponent(jLabel25)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_LoadLocDir, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(jButton_LoadLocData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_DriftCorrGroupFrameNum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jButton_Rerend, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_LoadLocData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_LocDataPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_LocDataDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_LoadLocDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                    .addComponent(jCheckBox_ShiftCorrection)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextField_DriftCorrGroupFrameNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton_Rerend, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("PostProc", jPanel4);

            jLabel19.setText("Parameters:");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(24, 24, 24))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents


    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
        int ErrorCodeI=0;
 //       if(ErrorCodeI!=0)return;
       

        GetLocalizationPara();

        
        fa_QC_STORM_.StartLocalization();
        
        // start to localize
        PluginStatus = 1;                            

        try {
            SavePropertyFile(GetParaFileSavePath());
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
            
        }       
    }//GEN-LAST:event_jButton_StartActionPerformed

    private void jButton_LoadParaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadParaFileActionPerformed
                
        OpenDialog dlgDialog=new OpenDialog("open para file");

        String filePath=dlgDialog.getPath();
        jTextField_ParaFile.setText(filePath);
        try {
            LoadPropertyFile(filePath);
            
        }catch (Exception ex) {
            
        }        
        
    }//GEN-LAST:event_jButton_LoadParaFileActionPerformed

    private void jButton_LoadResultPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadResultPathActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();  
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);  
        jf.showDialog(null,null);  
        File fi = jf.getSelectedFile();  
        ResultsFilePath = fi.getAbsolutePath();  
        
        char EndMarkC = '\\';
        if(ResultsFilePath.charAt(ResultsFilePath.length()-1)!=EndMarkC)
        {
            ResultsFilePath+=EndMarkC;
        }
        
        jTextField_ResultPath.setText(ResultsFilePath);
                
        
    }//GEN-LAST:event_jButton_LoadResultPathActionPerformed

    private void jButton_LoadLocDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadLocDataActionPerformed
                
        OpenDialog dlgDialog = new OpenDialog("open localization result file");

        String filePath = dlgDialog.getPath();
        jTextField_LocDataPath.setText(filePath);
        jTextField_LocDataDir.setText("");
        RerendLocDataPath = filePath;

        RerendMode = 0;
    }//GEN-LAST:event_jButton_LoadLocDataActionPerformed

    private void jButton_RerendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RerendActionPerformed
       
        if(RerendLocDataPath==null)return;
        
        if(RerendLocDataPath.length() < 2 )return;
        
        if(RerendMode == 0)
        {
            if(!RerendLocDataPath.endsWith(".txt"))
            {
                return;
            }
        }
        
        DriftCorrEnableI = jCheckBox_ShiftCorrection.isSelected()? 1 : 0;
        DriftCorrGroupFrameNum = Integer.parseInt(jTextField_DriftCorrGroupFrameNum.getText());
        
        
        DisableRerend();
        
        try {
            fa_QC_STORM_.StartRerend();  
            
            
        } catch (Exception ex) {

        }
        
        try {
            SavePropertyFile(GetParaFileSavePath());
        }catch (Exception ex) {
            
        }
        
        
        
    }//GEN-LAST:event_jButton_RerendActionPerformed

    private void jButton_Start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Start2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Start2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       

        
    }//GEN-LAST:event_formWindowClosing

    private void jTextField_RenderPixelSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RenderPixelSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RenderPixelSizeActionPerformed

    private void jComboBox_LocTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_LocTypeActionPerformed
        // TODO add your handling code here:
//        GetLocalizationPara();
        
    }//GEN-LAST:event_jComboBox_LocTypeActionPerformed

    private void jComboBox_RegionSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RegionSizeActionPerformed
        // TODO add your handling code here:
 //       GetLocalizationPara();
    }//GEN-LAST:event_jComboBox_RegionSizeActionPerformed

    private void jCheckBox_Stat_OntimeVaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Stat_OntimeVaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Stat_OntimeVaryActionPerformed

    private void jTextField_StructureSize2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_StructureSize2DActionPerformed
        // TODO add your handling code here:
        float StructureWidth = Float.parseFloat(jTextField_StructureSize2D.getText());

    }//GEN-LAST:event_jTextField_StructureSize2DActionPerformed

    private void jCheckBox_Stat_NyqResolutionVaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Stat_NyqResolutionVaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_Stat_NyqResolutionVaryActionPerformed

    private void jButton_LoadLocDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadLocDirActionPerformed
        // TODO add your handling code here:

        String Path = jTextField_LocDataDir.getText();
        
        JFileChooser jf;
        
        if(Path.length()>5)
        {
            jf = new JFileChooser(Path);  
        }else
        {
            jf = new JFileChooser();  
        }
        
        
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);  
        jf.showDialog(null,null);  
        File fi = jf.getSelectedFile();  
        
        RerendLocDataPath = fi.getAbsolutePath();
        
        
        jTextField_LocDataPath.setText("");
        jTextField_LocDataDir.setText(RerendLocDataPath);
        
        RerendMode = 1;
    }//GEN-LAST:event_jButton_LoadLocDirActionPerformed

    private void jComboBox_DH_RotationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DH_RotationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DH_RotationTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QC_STORM_Configurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QC_STORM_Configurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QC_STORM_Configurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QC_STORM_Configurator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QC_STORM_Configurator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LoadLocData;
    private javax.swing.JButton jButton_LoadLocDir;
    private javax.swing.JButton jButton_LoadParaFile;
    private javax.swing.JButton jButton_LoadResultPath;
    private javax.swing.JButton jButton_Rerend;
    private javax.swing.JButton jButton_Start;
    private javax.swing.JButton jButton_Start2;
    private javax.swing.JCheckBox jCheckBox_ShiftCorrection;
    private javax.swing.JCheckBox jCheckBox_Stat_BackgroundVary;
    private javax.swing.JCheckBox jCheckBox_Stat_ConsecutiveFitEn;
    private javax.swing.JCheckBox jCheckBox_Stat_DimensionFDVary;
    private javax.swing.JCheckBox jCheckBox_Stat_LocDensityFDVary;
    private javax.swing.JCheckBox jCheckBox_Stat_LocDensityVary;
    private javax.swing.JCheckBox jCheckBox_Stat_LocPrec;
    private javax.swing.JCheckBox jCheckBox_Stat_LocPrecVary;
    private javax.swing.JCheckBox jCheckBox_Stat_MultiFitEn;
    private javax.swing.JCheckBox jCheckBox_Stat_NyqResolutionVary;
    private javax.swing.JCheckBox jCheckBox_Stat_OntimeVary;
    private javax.swing.JCheckBox jCheckBox_Stat_PSFWidth;
    private javax.swing.JCheckBox jCheckBox_Stat_PSFWidthVary;
    private javax.swing.JCheckBox jCheckBox_Stat_SNR;
    private javax.swing.JCheckBox jCheckBox_Stat_SNRVary;
    private javax.swing.JCheckBox jCheckBox_Stat_SpaResolutionEn;
    private javax.swing.JCheckBox jCheckBox_Stat_SpaResolutionVary;
    private javax.swing.JCheckBox jCheckBox_Stat_TotalPhoton;
    private javax.swing.JCheckBox jCheckBox_Stat_TotalPhotonVary;
    private javax.swing.JCheckBox jCheckBox_Stat_WLEDisable;
    private javax.swing.JComboBox jComboBox_DH_RotationType;
    private javax.swing.JComboBox jComboBox_LocType;
    private javax.swing.JComboBox jComboBox_RegionSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_ROMP;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_ConsecFilterRadius;
    private javax.swing.JTextField jTextField_DH_DistanceTh;
    private javax.swing.JTextField jTextField_DH_MeanDistance;
    private javax.swing.JTextField jTextField_DriftCorrGroupFrameNum;
    private javax.swing.JTextField jTextField_Kadc;
    private javax.swing.JTextField jTextField_LocDataDir;
    private javax.swing.JTextField jTextField_LocDataPath;
    private javax.swing.JTextField jTextField_MaxZDepth;
    private javax.swing.JTextField jTextField_MinZDepth;
    private javax.swing.JTextField jTextField_Offset;
    private javax.swing.JTextField jTextField_ParaFile;
    private javax.swing.JTextField jTextField_ParaFile1;
    private javax.swing.JTextField jTextField_QE;
    private javax.swing.JTextField jTextField_RawPixelSize;
    private javax.swing.JTextField jTextField_RenderPixelSize;
    private javax.swing.JTextField jTextField_ResultPath;
    private javax.swing.JTextField jTextField_SNR_th;
    private javax.swing.JTextField jTextField_StructureSize2D;
    private javax.swing.JTextField jTextField_ZDepthCorrFactor;
    private javax.swing.JTextField jTextField_p0_XGY;
    private javax.swing.JTextField jTextField_p0_XLY;
    private javax.swing.JTextField jTextField_p1_XGY;
    private javax.swing.JTextField jTextField_p1_XLY;
    private javax.swing.JTextField jTextField_p2_XGY;
    private javax.swing.JTextField jTextField_p2_XLY;
    private javax.swing.JTextField jTextField_p2_XLY1;
    private javax.swing.JTextField jTextField_p3_XGY;
    private javax.swing.JTextField jTextField_p3_XLY;
    private javax.swing.JTextField jTextField_p4_XGY;
    private javax.swing.JTextField jTextField_p4_XLY;
    // End of variables declaration//GEN-END:variables
    

    
    public QC_STORM_Parameters.LocalizationPara GetLocalizationPara()
    {
        LocPara.Kadc   	= Float.parseFloat(jTextField_Kadc.getText());
        LocPara.Offset 	= Float.parseFloat(jTextField_Offset.getText());
        LocPara.QE 		= Float.parseFloat(jTextField_QE.getText());
        LocPara.RegionSize = Integer.parseInt((String)jComboBox_RegionSize.getSelectedItem());

    	LocPara.RawImgPixelSize = Float.parseFloat(jTextField_RawPixelSize.getText());
    	LocPara.RenderingPixelSize = Float.parseFloat(jTextField_RenderPixelSize.getText());
        LocPara.RenderingPixelZoom = LocPara.RawImgPixelSize/LocPara.RenderingPixelSize;
            
        LocPara.LocType = jComboBox_LocType.getSelectedIndex();
        
        
        LocPara.MultiEmitterFitEn = jCheckBox_Stat_MultiFitEn.isSelected()? 1 : 0;
        
        LocPara.WLEEn = jCheckBox_Stat_WLEDisable.isSelected()? 0 : 1;
        
        
        LocPara.ConsecutiveFitEn = jCheckBox_Stat_ConsecutiveFitEn.isSelected()? 1 : 0;
        LocPara.ConsecFilterRadius = Float.parseFloat(jTextField_ConsecFilterRadius.getText());
        
        LocPara.MinZDepth = Float.parseFloat(jTextField_MinZDepth.getText());
    	LocPara.MaxZDepth = Float.parseFloat(jTextField_MaxZDepth.getText());
        
        LocPara.ZDepthCorrFactor = Float.parseFloat(jTextField_ZDepthCorrFactor.getText());
        
    	LocPara.p4_XGY = Float.parseFloat(jTextField_p4_XGY.getText());
    	LocPara.p3_XGY = Float.parseFloat(jTextField_p3_XGY.getText());
    	LocPara.p2_XGY = Float.parseFloat(jTextField_p2_XGY.getText());
    	LocPara.p1_XGY = Float.parseFloat(jTextField_p1_XGY.getText());
    	LocPara.p0_XGY = Float.parseFloat(jTextField_p0_XGY.getText());

    	LocPara.p4_XLY = Float.parseFloat(jTextField_p4_XLY.getText());
    	LocPara.p3_XLY = Float.parseFloat(jTextField_p3_XLY.getText());
    	LocPara.p2_XLY = Float.parseFloat(jTextField_p2_XLY.getText());
    	LocPara.p1_XLY = Float.parseFloat(jTextField_p1_XLY.getText());
    	LocPara.p0_XLY = Float.parseFloat(jTextField_p0_XLY.getText());
               
        // double helix special
        
        LocPara.RotationType = jComboBox_DH_RotationType.getSelectedIndex();
        LocPara.MeanDistance = Float.parseFloat(jTextField_DH_MeanDistance.getText());
        LocPara.DistanceTh = Float.parseFloat(jTextField_DH_DistanceTh.getText());
        
        //
    	LocPara.SNR_th = Float.parseFloat(jTextField_SNR_th.getText());
        
        // spatial resolution
       
        LocPara.StructureSize2D = Float.parseFloat(jTextField_StructureSize2D.getText());
        
        // statastic information display enable
        LocPara.StatDispSel = GetStasticalInfDispEn();
        LocPara.SpatialResolutionEn = jCheckBox_Stat_SpaResolutionEn.isSelected() ? 1 : 0;
        
        LocPara.SpatialResolutionEn = 0;

        // save file path
        ResultsFilePath = jTextField_ResultPath.getText();  
        
        return LocPara;
    }
    
    void SendLocalizationPara()
    {
        GetLocalizationPara();
        
        QC_STORM_.lm_SetLocPara(LocPara.Kadc,LocPara.Offset,LocPara.QE,LocPara.RegionSize,LocPara.LocType, LocPara.MultiEmitterFitEn, LocPara.WLEEn, LocPara.ConsecutiveFitEn, LocPara.ConsecFilterRadius, LocPara.RawImgPixelSize,LocPara.RenderingPixelZoom,LocPara.SNR_th);
        
        QC_STORM_.lm_SetLocPara3D(LocPara.MinZDepth, LocPara.MaxZDepth, LocPara.ZDepthCorrFactor, LocPara.p4_XGY, LocPara.p3_XGY, LocPara.p2_XGY, LocPara.p1_XGY, LocPara.p0_XGY, LocPara.p4_XLY, LocPara.p3_XLY, LocPara.p2_XLY, LocPara.p1_XLY, LocPara.p0_XLY);
        QC_STORM_.lm_SetLocParaDH3D(LocPara.RotationType, LocPara.MeanDistance, LocPara.DistanceTh);
        
        
        QC_STORM_.lm_SetStatInfSelection(LocPara.StatDispSel, LocPara.SpatialResolutionEn);            
        QC_STORM_.lm_SetSpatialResolutionInf(LocPara.StructureSize2D);
                     
    }
    
    public int GetStasticalInfDispEn()
    {
        int InfDispSel = 0;

        // histgram
        if(jCheckBox_Stat_TotalPhoton.isSelected()) 	 InfDispSel |= 0x01;
        if(jCheckBox_Stat_LocPrec.isSelected())     	 InfDispSel |= 0x01<<1;
        if(jCheckBox_Stat_SNR.isSelected())         	 InfDispSel |= 0x01<<2;
        if(jCheckBox_Stat_PSFWidth.isSelected())    	 InfDispSel |= 0x01<<3;
        // time variation
        if(jCheckBox_Stat_TotalPhotonVary.isSelected())  InfDispSel |= 0x01<<4;
        if(jCheckBox_Stat_LocPrecVary.isSelected())      InfDispSel |= 0x01<<5;
        if(jCheckBox_Stat_OntimeVary.isSelected())       InfDispSel |= 0x01<<6;
        if(jCheckBox_Stat_SNRVary.isSelected())          InfDispSel |= 0x01<<7;   

        if(jCheckBox_Stat_PSFWidthVary.isSelected())     InfDispSel |= 0x01<<8;
        if(jCheckBox_Stat_LocDensityVary.isSelected())    InfDispSel |= 0x01<<9;
        if(jCheckBox_Stat_BackgroundVary.isSelected())   InfDispSel |= 0x01<<10;   
        
        // spatial resolution
        if(jCheckBox_Stat_SpaResolutionVary.isSelected())InfDispSel |= 0x01<<11;  
        if(jCheckBox_Stat_NyqResolutionVary.isSelected())InfDispSel |= 0x01<<12;
        if(jCheckBox_Stat_DimensionFDVary.isSelected())InfDispSel |= 0x01<<13;    
        if(jCheckBox_Stat_LocDensityFDVary.isSelected())InfDispSel |= 0x01<<14;
         
        
        return InfDispSel;
    }

    public void LoadPropertyFile(String FilePath) throws FileNotFoundException, IOException
    {
  
        File Parafile = new File(FilePath);
        File Parafiledir = new File(Parafile.getParent());


        if (Parafiledir.exists())
        {
           
        }else
        {
             Parafiledir.mkdirs();
        }

        if (Parafile.exists())
        {
            
        }else
        {
             Parafile.createNewFile();
        }
        

        // load property file
        
		Properties pps = new Properties();

		InputStream in = new FileInputStream(FilePath);
		
        
		pps.load(in);

		// with default value
       	jTextField_Kadc.setText(pps.getProperty("Kadc", Float.toString(LocPara.Kadc)));
		jTextField_Offset.setText(pps.getProperty("Offset", Float.toString(LocPara.Offset)));
		jTextField_QE.setText(pps.getProperty("QE", Float.toString(LocPara.QE)));

		jComboBox_RegionSize.setSelectedItem(pps.getProperty("RegionSize", Integer.toString(LocPara.RegionSize)));

		jTextField_RawPixelSize.setText(pps.getProperty("RawPixelSize", Float.toString(LocPara.RawImgPixelSize)));
		jTextField_RenderPixelSize.setText(pps.getProperty("RenderingPixelSize", Float.toString(LocPara.RenderingPixelSize)));

        jComboBox_LocType.setSelectedIndex(Integer.parseInt(pps.getProperty("LocType", Integer.toString(LocPara.LocType))));
        
        jCheckBox_Stat_MultiFitEn.setSelected(Boolean.parseBoolean(pps.getProperty("MultiEmitterFitEn", "true")));
        
        jCheckBox_Stat_WLEDisable.setSelected(!Boolean.parseBoolean(pps.getProperty("WLEEn", "true")));

        jCheckBox_Stat_ConsecutiveFitEn.setSelected(Boolean.parseBoolean(pps.getProperty("ConsecutiveFitEnable", "false")));
        jTextField_ConsecFilterRadius.setText(pps.getProperty("ConsecFilterRadius", Float.toString(80.0f)));

        
        jTextField_MinZDepth.setText(pps.getProperty("MinZDepth", Float.toString(LocPara.MinZDepth)));
        jTextField_MaxZDepth.setText(pps.getProperty("MaxZDepth", Float.toString(LocPara.MaxZDepth)));
        jTextField_ZDepthCorrFactor.setText(pps.getProperty("ZDepthCorrFactor", Float.toString(LocPara.ZDepthCorrFactor)));

        
		jTextField_p4_XGY.setText(pps.getProperty("p4_XGY", Float.toString(LocPara.p4_XGY)));
		jTextField_p3_XGY.setText(pps.getProperty("p3_XGY", Float.toString(LocPara.p3_XGY)));
		jTextField_p2_XGY.setText(pps.getProperty("p2_XGY", Float.toString(LocPara.p2_XGY)));
		jTextField_p1_XGY.setText(pps.getProperty("p1_XGY", Float.toString(LocPara.p1_XGY)));
		jTextField_p0_XGY.setText(pps.getProperty("p0_XGY", Float.toString(LocPara.p0_XGY)));

		jTextField_p4_XLY.setText(pps.getProperty("p4_XLY", Float.toString(LocPara.p4_XLY)));
		jTextField_p3_XLY.setText(pps.getProperty("p3_XLY", Float.toString(LocPara.p3_XLY)));
		jTextField_p2_XLY.setText(pps.getProperty("p2_XLY", Float.toString(LocPara.p2_XLY)));
		jTextField_p1_XLY.setText(pps.getProperty("p1_XLY", Float.toString(LocPara.p1_XLY)));
		jTextField_p0_XLY.setText(pps.getProperty("p0_XLY", Float.toString(LocPara.p0_XLY)));

        // double-helix special
        jComboBox_DH_RotationType.setSelectedIndex(Integer.parseInt(pps.getProperty("DH3D_RotationType", Integer.toString(LocPara.RotationType))));
        jTextField_DH_MeanDistance.setText(pps.getProperty("DH3D_MeanDistance", Float.toString(LocPara.MeanDistance)));
        jTextField_DH_DistanceTh.setText(pps.getProperty("DH3D_DistanceTh", Float.toString(LocPara.DistanceTh)));
        

        //
		jTextField_SNR_th.setText(pps.getProperty("SNR_thF", Float.toString(LocPara.SNR_th)));
        
        jTextField_StructureSize2D.setText(pps.getProperty("StructureSize2D", Float.toString(50.0f)));
        
        // statastic information display enable

        jCheckBox_Stat_TotalPhoton.setSelected(Boolean.parseBoolean(pps.getProperty("TPhotonEnable",Boolean.toString(false))));
        jCheckBox_Stat_LocPrec.setSelected(Boolean.parseBoolean(pps.getProperty("LocPrecEnable", Boolean.toString(false))));
        jCheckBox_Stat_SNR.setSelected(Boolean.parseBoolean(pps.getProperty("SNREnable", Boolean.toString(false))));
        jCheckBox_Stat_PSFWidth.setSelected(Boolean.parseBoolean(pps.getProperty("PSFEnable", Boolean.toString(false))));
        //
        jCheckBox_Stat_TotalPhotonVary.setSelected(Boolean.parseBoolean(pps.getProperty("TPhotonVariationEnable", Boolean.toString(true))));
        jCheckBox_Stat_LocPrecVary.setSelected(Boolean.parseBoolean(pps.getProperty("LocPrecVariationEnable", Boolean.toString(true))));
        jCheckBox_Stat_OntimeVary.setSelected(Boolean.parseBoolean(pps.getProperty("OntimeVariationEnable", Boolean.toString(false))));
        jCheckBox_Stat_SNRVary.setSelected(Boolean.parseBoolean(pps.getProperty("SNRVariationEnable", Boolean.toString(true))));
        jCheckBox_Stat_PSFWidthVary.setSelected(Boolean.parseBoolean(pps.getProperty("PSFWidthVariationEnable", Boolean.toString(true))));
        jCheckBox_Stat_LocDensityVary.setSelected(Boolean.parseBoolean(pps.getProperty("ActivationDensityVariationEnable", Boolean.toString(true))));
        jCheckBox_Stat_BackgroundVary.setSelected(Boolean.parseBoolean(pps.getProperty("BackgroundVariationEnable", Boolean.toString(false))));
        //
        jCheckBox_Stat_SpaResolutionVary.setSelected(Boolean.parseBoolean(pps.getProperty("SpaResolutionVaryEnable", Boolean.toString(false))));
        jCheckBox_Stat_NyqResolutionVary.setSelected(Boolean.parseBoolean(pps.getProperty("NyqResolutionVaryEnable", Boolean.toString(false))));

        jCheckBox_Stat_DimensionFDVary.setSelected(Boolean.parseBoolean(pps.getProperty("DimensionFDVaryEnable", Boolean.toString(false))));
        jCheckBox_Stat_LocDensityFDVary.setSelected(Boolean.parseBoolean(pps.getProperty("LocDensityFDVary", Boolean.toString(false))));
        
                
        jCheckBox_Stat_SpaResolutionEn.setSelected(Boolean.parseBoolean(pps.getProperty("SpaResolutionCalcEnable", Boolean.toString(false))));

    
       //
        jCheckBox_ShiftCorrection.setSelected(Boolean.parseBoolean(pps.getProperty("DriftCorrectionEn", Boolean.toString(true))));
        jTextField_DriftCorrGroupFrameNum.setText(pps.getProperty("DriftCorrGroupFrameNum", Integer.toString(1000)));

        //
        ResultsFilePath=pps.getProperty("ResultsFilePath", ResultsFilePath);
        
        if(!IsSavePathValid(ResultsFilePath))
        {
            ResultsFilePath = QC_STORM_Parameters.SelectDisk();
        }
        
        jTextField_ResultPath.setText(ResultsFilePath);
        
        
    }


    public void SavePropertyFile(String filePath) throws FileNotFoundException, IOException
    {
        if(filePath==null)return;

        
        Properties pps = new Properties();
        OutputStream out = new FileOutputStream(filePath);

        pps.setProperty("Kadc", jTextField_Kadc.getText());
        pps.setProperty("Offset", jTextField_Offset.getText());
        pps.setProperty("QE", jTextField_QE.getText());

        pps.setProperty("RegionSize", (String)jComboBox_RegionSize.getSelectedItem());

        pps.setProperty("RawPixelSize", jTextField_RawPixelSize.getText());
        pps.setProperty("RenderingPixelSize", jTextField_RenderPixelSize.getText());
        
        pps.setProperty("LocType", Integer.toString(jComboBox_LocType.getSelectedIndex()));

        
        pps.setProperty("MultiEmitterFitEn", Boolean.toString(LocPara.MultiEmitterFitEn!=0));
        pps.setProperty("WLEEn", Boolean.toString(LocPara.WLEEn!=0));
        pps.setProperty("ConsecutiveFitEnable", Boolean.toString(LocPara.ConsecutiveFitEn!=0));

        
        pps.setProperty("ConsecFilterRadius", jTextField_ConsecFilterRadius.getText());
        
        
        pps.setProperty("MinZDepth", jTextField_MinZDepth.getText());
        pps.setProperty("MaxZDepth", jTextField_MaxZDepth.getText());
        pps.setProperty("ZDepthCorrFactor", jTextField_ZDepthCorrFactor.getText());
        
        
        pps.setProperty("p4_XGY", jTextField_p4_XGY.getText());
        pps.setProperty("p3_XGY", jTextField_p3_XGY.getText());
        pps.setProperty("p2_XGY", jTextField_p2_XGY.getText());
        pps.setProperty("p1_XGY", jTextField_p1_XGY.getText());
        pps.setProperty("p0_XGY", jTextField_p0_XGY.getText());

        pps.setProperty("p4_XLY", jTextField_p4_XLY.getText());
        pps.setProperty("p3_XLY", jTextField_p3_XLY.getText());
        pps.setProperty("p2_XLY", jTextField_p2_XLY.getText());
        pps.setProperty("p1_XLY", jTextField_p1_XLY.getText());
        pps.setProperty("p0_XLY", jTextField_p0_XLY.getText());
        
        // double-helix special
        pps.setProperty("DH3D_RotationType", Integer.toString(jComboBox_DH_RotationType.getSelectedIndex()));
        pps.setProperty("DH3D_MeanDistance", jTextField_DH_MeanDistance.getText());
        pps.setProperty("DH3D_DistanceTh", jTextField_DH_DistanceTh.getText());
        
        
        //
        pps.setProperty("SNR_thF", jTextField_SNR_th.getText());
        
        pps.setProperty("StructureSize2D", jTextField_StructureSize2D.getText());
        
        // statastic information display enable
        pps.setProperty("TPhotonEnable", Boolean.toString(jCheckBox_Stat_TotalPhoton.isSelected()));
        pps.setProperty("LocPrecEnable", Boolean.toString(jCheckBox_Stat_LocPrec.isSelected()));
        pps.setProperty("SNREnable", Boolean.toString(jCheckBox_Stat_SNR.isSelected()));
        pps.setProperty("PSFEnable", Boolean.toString(jCheckBox_Stat_PSFWidth.isSelected()));

        pps.setProperty("TPhotonVariationEnable", Boolean.toString(jCheckBox_Stat_TotalPhotonVary.isSelected()));
        pps.setProperty("LocPrecVariationEnable", Boolean.toString(jCheckBox_Stat_LocPrecVary.isSelected()));
        pps.setProperty("OntimeVariationEnable", Boolean.toString(jCheckBox_Stat_OntimeVary.isSelected()));
        pps.setProperty("SNRVariationEnable", Boolean.toString(jCheckBox_Stat_SNRVary.isSelected()));        
        pps.setProperty("PSFWidthVariationEnable", Boolean.toString(jCheckBox_Stat_PSFWidthVary.isSelected()));
        pps.setProperty("ActivationDensityVariationEnable", Boolean.toString(jCheckBox_Stat_LocDensityVary.isSelected()));
        pps.setProperty("BackgroundVariationEnable", Boolean.toString(jCheckBox_Stat_BackgroundVary.isSelected()));       
        //
        pps.setProperty("SpaResolutionVaryEnable", Boolean.toString(jCheckBox_Stat_SpaResolutionVary.isSelected()));
        pps.setProperty("NyqResolutionVaryEnable", Boolean.toString(jCheckBox_Stat_NyqResolutionVary.isSelected()));        
        
        pps.setProperty("DimensionFDVaryEnable", Boolean.toString(jCheckBox_Stat_DimensionFDVary.isSelected()));
        pps.setProperty("LocDensityFDVary", Boolean.toString(jCheckBox_Stat_LocDensityFDVary.isSelected()));        

        
        pps.setProperty("SpaResolutionCalcEnable", Boolean.toString(jCheckBox_Stat_SpaResolutionEn.isSelected()));        
        
        
        pps.setProperty("DriftCorrectionEn", Boolean.toString(jCheckBox_ShiftCorrection.isSelected()));
        pps.setProperty("DriftCorrGroupFrameNum", jTextField_DriftCorrGroupFrameNum.getText());
        
        //
        pps.setProperty("ResultsFilePath", ResultsFilePath);

    	pps.store(out, "Localization para");

    }
    
    public String GetResultsSavePath()
    {
        return jTextField_ResultPath.getText();
    } 
    
    public String GetParaFileSavePath()
    {
        String ParaFilePath = QC_STORM_Parameters.SelectDisk();
        return ParaFilePath + LocParafileName;
    }    
    
    public boolean IsSavePathValid(String iPath)
    {
        File f = new File(iPath);
        boolean Valid = f.exists();
        
        return Valid;
    }

    public void EnableRerend()
    {
        jButton_Rerend.setEnabled(true);
    }
    
    public void DisableRerend()
    {
        jButton_Rerend.setEnabled(false);
    }

    
    public class MyListener implements WindowListener
    {

        @Override
        public void windowOpened(WindowEvent e) {
            
        }

        @Override
        public void windowClosing(WindowEvent e) {
            
            // closed
            PluginStatus = 2;

        }

        @Override
        public void windowClosed(WindowEvent e) {

        }

        @Override
        public void windowIconified(WindowEvent e) {
 
        }

        @Override
        public void windowDeiconified(WindowEvent e) {

        }

        @Override
        public void windowActivated(WindowEvent e) {

        }

        @Override
        public void windowDeactivated(WindowEvent e) {

        }
        
    }

}
